<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyPowerTools.Abstractions\MyPowerTools.Abstractions.csproj" />
    <ProjectReference Include="..\MyPowerTools.Protocol\MyPowerTools.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ModulePackageRoot>$(MSBuildProjectDirectory)\..\..\modules\smartbird-thermostat</ModulePackageRoot>
  </PropertyGroup>

  <Target Name="CopyModuleAssemblyToPackage" AfterTargets="Build">
    <MakeDir Directories="$(ModulePackageRoot)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModulePackageRoot)" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(ModulePackageRoot)" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
  </Target>

</Project>
